# Generated by Django 3.2.5 on 2021-09-22 15:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_management', '0001_initial'),
        ('location_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('manufacture', models.CharField(blank=True, max_length=255, null=True)),
                ('vile_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('date_given', models.DateField(blank=True, null=True)),
                ('admister_person', models.CharField(blank=True, max_length=255, null=True)),
                ('arm', models.CharField(blank=True, max_length=255, null=True)),
                ('dose_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=255, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.appointment')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.location')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient')),
            ],
        ),
    ]
