# Generated by Django 3.2.9 on 2021-11-28 16:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0003_auto_20211128_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='vaccination_id',
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
