# Generated by Django 3.2.9 on 2021-12-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0005_auto_20211202_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccination',
            options={'ordering': ['-date_given']},
        ),
    ]
