# Generated by Django 3.2.9 on 2021-12-02 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetaccount',
            name='expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 2, 16, 41, 51, 774858, tzinfo=utc), null=True),
        ),
    ]
