# Generated by Django 3.2.5 on 2021-09-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='can_receive_location_batch',
            field=models.BooleanField(default=False),
        ),
    ]
