# Generated by Django 3.2.9 on 2021-12-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_can_receive_location_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'Staff Account'},
        ),
    ]
