# Generated by Django 3.2.9 on 2021-12-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_useraccount_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
    ]
