# Generated by Django 3.2.9 on 2021-12-02 15:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_resetaccount_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetaccount',
            name='expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 2, 16, 43, 1, 965727, tzinfo=utc), null=True),
        ),
    ]
