# Generated by Django 3.2.9 on 2021-12-03 02:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_resetaccount_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetaccount',
            name='expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 3, 9, 41, 910355, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
