# Generated by Django 3.2.9 on 2021-12-03 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211202_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetaccount',
            name='expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 13, 34, 37, 689005, tzinfo=utc), null=True),
        ),
    ]
