# Generated by Django 3.2.9 on 2021-12-03 12:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_resetaccount_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetaccount',
            name='expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 13, 52, 57, 25952, tzinfo=utc), null=True),
        ),
    ]
