# Generated by Django 3.2.9 on 2021-12-03 12:56

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_resetaccount_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetaccount',
            name='expires',
            field=models.DateTimeField(blank=True, default=account.models.expire_gen, null=True),
        ),
    ]
