# Generated by Django 3.2.5 on 2021-09-29 19:09

from django.db import migrations, models
import location_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='authorization_code',
            field=models.CharField(default=location_management.models.codeGenerator, max_length=8),
        ),
    ]
