# Generated by Django 3.2.9 on 2021-11-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0003_alter_location_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='role',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='role',
        ),
        migrations.RemoveField(
            model_name='test',
            name='role',
        ),
    ]
