# Generated by Django 3.2.9 on 2021-11-28 01:31

from django.db import migrations, models
import location_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0004_auto_20211127_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='shorten_id',
            field=models.CharField(blank=True, default=location_management.models.shorten_id_generator, max_length=6, null=True),
        ),
    ]
