# Generated by Django 3.2.9 on 2021-12-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0006_alter_appointment_shorten_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Site'},
        ),
    ]
