# Generated by Django 3.2.9 on 2021-12-03 12:34

from django.db import migrations, models
import location_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0008_auto_20211202_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='shorten_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='authorization_code',
            field=models.CharField(default=location_management.models.codeGenerator, max_length=8, unique=True),
        ),
    ]
