# Generated by Django 3.2.9 on 2021-12-03 13:04

from django.db import migrations, models
import location_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0009_auto_20211203_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='shorten_id',
            field=models.CharField(blank=True, default=location_management.models.shorten_id_generator, max_length=6, null=True, unique=True),
        ),
    ]
