# Generated by Django 3.2.9 on 2021-12-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0014_alter_appointment_shorten_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
