# Generated by Django 3.2.9 on 2021-12-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0017_alter_appointment_shorten_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='shorten_id',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
    ]
