# Generated by Django 3.2.9 on 2021-12-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0019_auto_20211203_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'Availabilities'},
        ),
    ]
