# Generated by Django 3.2.9 on 2021-12-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0020_alter_availability_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
