# Generated by Django 3.2.5 on 2021-09-23 18:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationBatch',
            fields=[
                ('batch_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number_of_dose', models.IntegerField()),
                ('status', models.CharField(default='Dispatched', max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_management.location')),
            ],
        ),
    ]
