# Generated by Django 3.2.5 on 2021-09-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_locationbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationbatch',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='batch_qr/'),
        ),
    ]
