# Generated by Django 3.2.5 on 2021-09-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_locationbatch_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationbatch',
            name='vaccine',
            field=models.CharField(default='Pfizer', max_length=255),
            preserve_default=False,
        ),
    ]
