# Generated by Django 3.2.5 on 2021-09-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_locationbatch_vaccine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine',
            old_name='type',
            new_name='label',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='role',
            field=models.CharField(default='Master', max_length=50),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='value',
            field=models.CharField(default='Pfizer', max_length=50),
            preserve_default=False,
        ),
    ]
