# Generated by Django 3.2.5 on 2021-09-24 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210924_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationbatch',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.vaccine'),
        ),
    ]
