# Generated by Django 3.2.5 on 2021-09-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_locationbatch_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationbatch',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
