# Generated by Django 3.2.5 on 2021-10-06 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_locationbatch_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationbatch',
            options={'ordering': ('-last_updated',)},
        ),
    ]
