# Generated by Django 3.2.9 on 2021-11-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_locationbatch_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationvaccine',
            name='role',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='role',
        ),
    ]
