# Generated by Django 3.2.9 on 2021-12-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20211127_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationbatch',
            options={'ordering': ('-date_created',), 'verbose_name': 'Site Batch', 'verbose_name_plural': 'Site Batches'},
        ),
        migrations.AlterModelOptions(
            name='locationvaccine',
            options={'verbose_name': 'Site Vaccine'},
        ),
        migrations.AlterField(
            model_name='locationbatch',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
