# Generated by Django 3.2.9 on 2021-12-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_locationbatch_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationbatch',
            name='status',
            field=models.CharField(default='Dispatched', max_length=50),
        ),
    ]
