# Generated by Django 3.2.5 on 2021-09-22 15:07

from django.db import migrations, models
import django.db.models.deletion
import patient_management.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='uploads/')),
                ('tax_number', models.CharField(max_length=150, null=True, unique=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('street_address', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('parish', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpdatePatientCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=patient_management.models.codeGenerator, max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PositiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovering_location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=patient_management.models.codeGenerator, max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient')),
            ],
        ),
    ]
