# Generated by Django 3.2.9 on 2022-02-15 00:11

from django.db import migrations, models
import django.db.models.deletion
import patient_management.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='uploads/')),
                ('identification', models.ImageField(blank=True, null=True, upload_to='uploads/identification/')),
                ('tax_number', models.CharField(max_length=12, null=True, unique=True)),
                ('title', models.CharField(max_length=15, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=75, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('street_address', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('parish', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpdatePatientCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=patient_management.models.codeGenerator, max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_first_name', models.CharField(max_length=50)),
                ('rep_last_name', models.CharField(max_length=50)),
                ('rep_email', models.EmailField(blank=True, max_length=75, null=True)),
                ('rep_phone', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveredCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_date', models.DateField()),
                ('last_updated', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PositiveCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tested', models.DateField(blank=True, null=True)),
                ('recovering_location', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Recovering', max_length=50)),
                ('last_updated', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=patient_management.models.codeGenerator, max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient')),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kin_first_name', models.CharField(max_length=50)),
                ('kin_last_name', models.CharField(max_length=50)),
                ('kin_email', models.EmailField(blank=True, max_length=75, null=True)),
                ('kin_phone', models.CharField(max_length=20)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalizedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalized_date', models.DateField()),
                ('last_updated', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DeathCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_date', models.DateField()),
                ('last_updated', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient')),
            ],
        ),
    ]
