# Generated by Django 3.2.9 on 2022-03-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='identification',
            field=models.FileField(blank=True, null=True, upload_to='uploads/identification/'),
        ),
    ]
