# Generated by Django 3.2.5 on 2021-10-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0002_auto_20211001_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
