# Generated by Django 3.2.5 on 2021-10-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0003_alter_nextofkin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
