# Generated by Django 3.2.5 on 2021-10-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0004_alter_nextofkin_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextofkin',
            old_name='email',
            new_name='kin_email',
        ),
        migrations.RenameField(
            model_name='nextofkin',
            old_name='first_name',
            new_name='kin_first_name',
        ),
        migrations.RenameField(
            model_name='nextofkin',
            old_name='last_name',
            new_name='kin_last_name',
        ),
        migrations.RenameField(
            model_name='nextofkin',
            old_name='phone',
            new_name='kin_phone',
        ),
    ]
