# Generated by Django 3.2.5 on 2021-10-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0005_auto_20211001_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='identification',
            field=models.FileField(upload_to='uploads/identification/'),
        ),
    ]
