# Generated by Django 3.2.5 on 2021-10-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0006_alter_patient_identification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PositiveStatus',
            new_name='PositiveCase',
        ),
    ]
