# Generated by Django 3.2.5 on 2021-10-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0007_rename_positivestatus_positivecase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positivecase',
            name='status',
            field=models.CharField(default='Recovering', max_length=255),
        ),
    ]
