# Generated by Django 3.2.5 on 2021-10-09 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0008_alter_positivecase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='positivecase',
            name='case_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
