# Generated by Django 3.2.5 on 2021-10-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0009_positivecase_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='positivecase',
            name='date_tested',
            field=models.DateField(blank=True, null=True),
        ),
    ]
