# Generated by Django 3.2.9 on 2021-11-28 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0010_positivecase_date_tested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_first_name', models.CharField(max_length=50)),
                ('rep_last_name', models.CharField(max_length=50)),
                ('rep_email', models.EmailField(blank=True, max_length=75, null=True)),
                ('rep_phone', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient')),
            ],
        ),
    ]
