# Generated by Django 3.2.9 on 2021-12-01 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0011_auto_20211127_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='positivecase',
            name='last_updated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
