# Generated by Django 3.2.9 on 2021-12-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0013_alter_positivecase_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positivecase',
            name='last_updated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
