# Generated by Django 3.2.9 on 2021-12-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0014_alter_positivecase_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='kin_email',
            field=models.EmailField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='kin_first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='kin_last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='kin_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=75, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='parish',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tax_number',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='title',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='positivecase',
            name='recovering_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='positivecase',
            name='status',
            field=models.CharField(default='Recovering', max_length=50),
        ),
    ]
