# Generated by Django 3.2.9 on 2021-12-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0015_auto_20211202_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=75, null=True),
        ),
    ]
