# Generated by Django 3.2.9 on 2021-12-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0018_hospitalizedcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positivecase',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
