# Generated by Django 3.2.9 on 2021-12-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0020_auto_20211204_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='identification',
            field=models.FileField(blank=True, null=True, upload_to='uploads/identification/'),
        ),
    ]
