# Generated by Django 3.2.9 on 2021-12-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0021_auto_20211204_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positivecase',
            old_name='id',
            new_name='case_id',
        ),
    ]
