# Generated by Django 3.2.9 on 2021-11-28 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20211128_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='testing_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='testing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
